### ISSUE TITLE
proxy redirect problem

### ISSUE THREAD

**Issue by persianphilosopher** [alexanderjulo/wiki#72]
This is pretty much the exact type of wiki I have been looking for. Admittedly, I had been searching for PHP/js packages because I am more familiar with those languages and forgive me if the following issue is due to my lack of experience with python.

I installed the wiki via pip - per the README.md, on a vps and most of everything works out of the box with a reverse proxy (using caddy).  

When I "create a page," however, it redirects to localhost:5000/edit/XYZ. 

On Nodejs, a problem like that is often solved by providing the site's url in settings and perhaps it would be the same here in the config.py but passing a "URL" field did not seem do the trick. 

Any suggestion for this redirect would be greatly appreciated. 

PS: is there a way to see all the variables that config.py accepts?

**Comment by alexanderjulo** [comment]
Wiki accepts [all flask config parameters](http://flask.pocoo.org/docs/0.12/config/)!

The relevant for you is `SERVER_NAME` which you should configure to whatever address your caddy is available at.

Feel free to re-open if this does not address your issue!
