### ISSUE TITLE
Change host

### ISSUE THREAD

**Issue by olavurmortensen** [alexanderjulo/wiki#73]
This wiki app uses localhost by default (127.0.0.1:5000). Is it possible to specify which host and port to use? I know that in Flask you do this with the  `--host` and `--port` flags.

**Comment by olavurmortensen** [comment]
So I figured out that it is possible to do this, but requires editing the code. In the `cli.py` file, the `app.run(debug=debug)` command takes a `host` and a `port` argument. If these were added to the "click" function decorators (similar to the `--debug` argument), then we could run `wiki web --host=1.2.3.4 --port=1234` or something like that.

**Comment by bmcculley** [comment]
This is now possible after merging #74, this issue can be closed.
